name: PEP8 check

on:
  push:
  pull_request:

jobs:
  pep8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install pycodestyle
        run: pip install pycodestyle

      - name: Run pycodestyle
        run: pycodestyle .
